import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { api, PulseSummary } from "@/src/api";
import { colors } from "@/src/theme";

export function Pulse60Screen() {
  const insets = useSafeAreaInsets();
  const [summary, setSummary] = useState<PulseSummary | null>(null);
  const [movement, setMovement] = useState("Some movement");
  const [nourishment, setNourishment] = useState("Nourished");
  const [wellbeing, setWellbeing] = useState("Checked in");
  const [reflection, setReflection] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { api.pulse().then(setSummary).catch(() => setMessage("We could not load your check-ins.")); }, []);
  const save = async () => { setBusy(true); setMessage(""); try { const result = await api.savePulse({ check_in_date: new Date().toISOString().slice(0, 10), movement, nourishment, wellbeing, reflection: reflection || null, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC" }); setSummary(result.summary); setMessage("Saved for today."); } catch (error) { setMessage(error instanceof Error ? error.message : "We could not save this check-in."); } finally { setBusy(false); } };
  return <ScrollView testID="pulse60-screen" style={styles.root} contentContainerStyle={[styles.content, { paddingTop: insets.top + 24 }]}><Text style={styles.eyebrow}>PULSE 60</Text><Text style={styles.title}>One minute for yourself.</Text><Text style={styles.subtitle}>Notice the small things. A photo is never required for a check-in to count.</Text><View style={styles.streakCard}><Text style={styles.cardLabel}>CURRENT STREAK</Text><Text style={styles.streak}>{summary?.streak ?? 0}<Text style={styles.streakUnit}> days</Text></Text><Text style={styles.cardNote}>Your progress is recalculated from saved check-ins.</Text></View><Text style={styles.sectionTitle}>Today’s check-in</Text><Choice label="Movement" value={movement} options={["Some movement", "A lot of movement", "Rest day"]} onChange={setMovement} /><Choice label="Nourishment" value={nourishment} options={["Nourished", "Learning", "Taking it easy"]} onChange={setNourishment} /><Choice label="Wellbeing" value={wellbeing} options={["Checked in", "Need a pause", "Need support"]} onChange={setWellbeing} /><Text style={styles.label}>Optional reflection</Text><TextInput testID="pulse60-reflection-input" value={reflection} onChangeText={setReflection} placeholder="Anything you want to remember?" placeholderTextColor={colors.muted} style={[styles.input, styles.multiline]} multiline maxLength={500} />{message ? <Text testID="pulse60-message" style={styles.message}>{message}</Text> : null}<Pressable testID="pulse60-save-button" disabled={busy} onPress={save} style={({ pressed }) => [styles.action, pressed && styles.pressed, busy && styles.disabled]}>{busy ? <ActivityIndicator color={colors.onBrandPrimary} /> : <Text style={styles.actionText}>{summary?.today ? "Update today’s check-in" : "Save today’s check-in"}</Text>}</Pressable><Text style={styles.sectionTitle}>Last seven days</Text><View style={styles.weekRow}>{(summary?.days ?? []).map((day) => <View key={day.date} style={styles.day}><View style={[styles.dayDot, day.complete && styles.complete]}><Text style={styles.check}>{day.complete ? "✓" : ""}</Text></View><Text style={styles.dayLabel}>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short" }).slice(0, 2)}</Text></View>)}</View></ScrollView>;
}

function Choice({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <View style={styles.choice}><Text style={styles.label}>{label}</Text><View style={styles.choiceRow}>{options.map((option) => <Pressable testID={`pulse60-choice-${label.toLowerCase()}-${option}`} key={option} onPress={() => onChange(option)} style={[styles.chip, value === option && styles.chipActive]}><Text style={[styles.chipText, value === option && styles.chipTextActive]}>{option}</Text></Pressable>)}</View></View>; }

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface }, content: { paddingHorizontal: 22, paddingBottom: 32 }, eyebrow: { color: colors.brandPrimary, fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, title: { color: colors.onSurface, fontSize: 30, fontWeight: "700", marginTop: 10 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8 }, streakCard: { marginTop: 24, backgroundColor: colors.surfaceInverse, borderRadius: 20, padding: 22 }, cardLabel: { color: colors.brandTertiary, fontSize: 11, fontWeight: "800", letterSpacing: 1 }, streak: { color: colors.onSurfaceInverse, fontSize: 54, fontWeight: "800", marginTop: 5 }, streakUnit: { fontSize: 19, fontWeight: "500" }, cardNote: { color: colors.muted, marginTop: 5 }, sectionTitle: { color: colors.onSurface, fontSize: 20, fontWeight: "700", marginTop: 30, marginBottom: 16 }, choice: { marginBottom: 17 }, label: { color: colors.onSurface, fontSize: 13, fontWeight: "700", marginBottom: 8 }, choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { minHeight: 42, paddingHorizontal: 13, borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSecondary, justifyContent: "center" }, chipActive: { borderColor: colors.brandPrimary, backgroundColor: colors.brandTertiary }, chipText: { color: colors.onSurfaceSecondary, fontSize: 13 }, chipTextActive: { color: colors.onBrandTertiary, fontWeight: "700" }, input: { minHeight: 50, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSecondary, color: colors.onSurface, padding: 14, fontSize: 15 }, multiline: { minHeight: 92, textAlignVertical: "top" }, message: { color: colors.info, marginTop: 12, lineHeight: 19 }, action: { minHeight: 52, backgroundColor: colors.brandPrimary, borderRadius: 26, alignItems: "center", justifyContent: "center", marginTop: 18 }, actionText: { color: colors.onBrandPrimary, fontWeight: "700" }, pressed: { opacity: 0.76 }, disabled: { opacity: 0.6 }, weekRow: { flexDirection: "row", justifyContent: "space-between" }, day: { alignItems: "center", gap: 7 }, dayDot: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.borderStrong, alignItems: "center", justifyContent: "center" }, complete: { backgroundColor: colors.success, borderColor: colors.success }, check: { color: colors.onSuccess, fontWeight: "800" }, dayLabel: { color: colors.muted, fontSize: 12 } });